# **1. Perkenalan Dataset**

## Sumber Data

Dataset yang digunakan dalam proyek ini merupakan **data primer** yang dikumpulkan secara langsung dari laporan keuangan operasional perusahaan. Data tersebut diperoleh melalui proses ekstraksi dan integrasi dari beberapa sumber internal perusahaan, yang meliputi:

* Laporan Arus Kas
* Laporan TO (Data tidak ambil obat)
* Laporan Transfer
* Laporan Closing dari Sistem Manajemen Perusahaan

Seluruh data kemudian melalui proses pembersihan (data cleaning), validasi, dan transformasi sehingga siap digunakan dalam proses analisis data dan pengembangan model machine learning.

Karena dataset berasal dari dokumen keuangan internal perusahaan, data ini mengandung informasi yang bersifat **rahasia dan sensitif**. Oleh karena itu, untuk menjaga keamanan serta kerahasiaan informasi, seluruh file data asli telah diamankan menggunakan **enkripsi GPG (GNU Privacy Guard)** sebelum disimpan maupun diproses dalam lingkungan pengembangan. Pendekatan ini memastikan bahwa hanya pihak yang memiliki kunci dekripsi yang berwenang yang dapat mengakses data mentah, sehingga privasi perusahaan tetap terjaga sesuai dengan praktik keamanan data yang baik.

Dalam repositori proyek ini, file yang tersedia merupakan **hasil enkripsi (.gpg)**, sedangkan data asli tidak dipublikasikan. Proses dekripsi dilakukan secara lokal oleh pengguna yang memiliki otorisasi sebelum tahap pemrosesan data dijalankan. Dengan demikian, proyek ini tetap mendukung prinsip **reproducibility** tanpa mengorbankan aspek **kerahasiaan, integritas, dan keamanan data perusahaan**.

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

# **2. Import Library**

Pada tahap ini, Anda perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning atau deep learning.

In [ ]:
import pandas as pd
import os

# **3. Memuat Dataset**

Pada tahap ini, Anda perlu memuat dataset ke dalam notebook. Jika dataset dalam format CSV, Anda bisa menggunakan pustaka pandas untuk membacanya. Pastikan untuk mengecek beberapa baris awal dataset untuk memahami strukturnya dan memastikan data telah dimuat dengan benar.

Jika dataset berada di Google Drive, pastikan Anda menghubungkan Google Drive ke Colab terlebih dahulu. Setelah dataset berhasil dimuat, langkah berikutnya adalah memeriksa kesesuaian data dan siap untuk dianalisis lebih lanjut.

Jika dataset berupa unstructured data, silakan sesuaikan dengan format seperti kelas Machine Learning Pengembangan atau Machine Learning Terapan

In [ ]:
# Define the path to your Google Drive folder
folder_path = '/content/gdrive/MyDrive/Data_Keuangan'

# List to store dataframes
all_dataframes = []

# Check if the folder exists
if os.path.exists(folder_path):
    # Iterate over files in the directory
    for filename in os.listdir(folder_path):
        # Check for common Excel file extensions
        if filename.endswith(('.xlsx', '.xls')):
            file_path = os.path.join(folder_path, filename)
            print(f"Reading Excel file: {file_path}")
            try:
                df = pd.read_excel(file_path)
                all_dataframes.append(df)
            except Exception as e:
                print(f"Error reading {filename}: {e}")

    if all_dataframes:
        print(f"Successfully read {len(all_dataframes)} Excel files.")
        # Example: Concatenate all dataframes into one if desired
        # combined_df = pd.concat(all_dataframes, ignore_index=True)
        # print("Combined DataFrame head:")
        # print(combined_df.head())
    else:
        print("No Excel files found or readable in the specified folder.")
else:
    print(f"Folder not found: {folder_path}. Please ensure Google Drive is mounted and the path is correct.")

# You can now work with 'all_dataframes' which is a list of pandas DataFrames

Reading Excel file: /content/gdrive/MyDrive/Data_Keuangan/Laporan kasir.xlsx
Reading Excel file: /content/gdrive/MyDrive/Data_Keuangan/ARUS KAS 2026.xlsx
Reading Excel file: /content/gdrive/MyDrive/Data_Keuangan/data sistem 1 - 31 mei.xlsx
Successfully read 3 Excel files.

# **4. Exploratory Data Analysis (EDA)**

Pada tahap ini, Anda akan melakukan **Exploratory Data Analysis (EDA)** untuk memahami karakteristik dataset.

Tujuan dari EDA adalah untuk memperoleh wawasan awal yang mendalam mengenai data dan menentukan langkah selanjutnya dalam analisis atau pemodelan.

## Data TO

In [ ]:
# Define the path to your Excel file
excel_file_path = '/content/gdrive/MyDrive/Data_Keuangan/Laporan kasir.xlsx'

# Define the name of the sheet you want to read
sheet_name = 'TO'  # e.g., 'Sheet2', 'My Data'

try:
    # Read the specified sheet from the Excel file into a DataFrame
    df_to = pd.read_excel(excel_file_path, sheet_name=sheet_name)
    print(f"Successfully read sheet '{sheet_name}' from '{excel_file_path}'.")
    print("First 5 rows of the DataFrame:")
    print(df_to.head())
except FileNotFoundError:
    print(f"Error: The file '{excel_file_path}' was not found. Please check the path.")
except ValueError as e:
    print(f"Error reading sheet '{sheet_name}': {e}. Please ensure the sheet name is correct.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

Successfully read sheet 'TO' from '/content/gdrive/MyDrive/Data_Keuangan/Laporan kasir.xlsx'.
First 5 rows of the DataFrame:
  LAPORAN PENDAPATAN HARIAN KASIR (PASIEN TIDAK AMBIL OBAT) Unnamed: 1  \
0                          dr. Doddy Pratama, Sp. OG               NaN
1                                2026-05-01 00:00:00               NaN
2                                                TGL                NO
3                                                NaN               NaN
4                                2026-05-01 00:00:00                 1

          Unnamed: 2 Unnamed: 3 Unnamed: 4   Unnamed: 5 Unnamed: 6 Unnamed: 7  \
0                NaN        NaN        NaN          NaN        NaN        NaN
1                NaN        NaN        NaN          NaN        NaN        NaN
2        NAMA PASIEN      BIAYA        NaN          NaN        NaN        NaN
3                NaN     KONSUL        ADM  USG (2/4) D   T.VERBAN       INSP
4  RATNA AYU LESTARI      90000      20000        40000        NaN        NaN

  Unnamed: 8 Unnamed: 9
0        NaN        NaN
1        NaN        NaN
2        NaN      TOTAL
3      USG V        NaN
4        NaN     150000

In [ ]:
df_to.head()

,LAPORAN PENDAPATAN HARIAN KASIR (PASIEN TIDAK AMBIL OBAT),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,"dr. Doddy Pratama, Sp. OG",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-05-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,TGL,NO,NAMA PASIEN,BIAYA,NaN,NaN,NaN,NaN,NaN,TOTAL
3,NaN,NaN,NaN,KONSUL,ADM,USG (2/4) D,T.VERBAN,INSP,USG V,NaN
4,2026-05-01 00:00:00,1,RATNA AYU LESTARI,90000,20000,40000,NaN,NaN,NaN,150000

In [ ]:
df_to.tail()

,LAPORAN PENDAPATAN HARIAN KASIR (PASIEN TIDAK AMBIL OBAT),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
93,NaN,NaN,NaN,Direktur,NaN,NaN,NaN,NaN,NaN,NaN
94,NaN,NaN,NaN,Disahkan Oleh,NaN,NaN,NaN,NaN,NaN,NaN
95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,NaN,NaN,NaN,"dr. Desvavri, MPH, CHMC",NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_to.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98 entries, 0 to 97
Data columns (total 10 columns):
 #   Column                                                     Non-Null Count  Dtype
---  ------                                                     --------------  -----
 0   LAPORAN PENDAPATAN HARIAN KASIR (PASIEN TIDAK AMBIL OBAT)  27 non-null     object
 1   Unnamed: 1                                                 83 non-null     object
 2   Unnamed: 2                                                 83 non-null     object
 3   Unnamed: 3                                                 87 non-null     object
 4   Unnamed: 4                                                 83 non-null     object
 5   Unnamed: 5                                                 81 non-null     object
 6   Unnamed: 6                                                 2 non-null      object
 7   Unnamed: 7                                                 3 non-null      object
 8   Unnamed: 8                                                 7 non-null      object
 9   Unnamed: 9                                                 84 non-null     object
dtypes: object(10)
memory usage: 7.8+ KB

## Data Transfer

In [ ]:
# Define the name of the sheet you want to read
sheet_name = 'TRANSFERAN'  # e.g., 'Sheet2', 'My Data'

try:
    # Read the specified sheet from the Excel file into a DataFrame
    df_tf = pd.read_excel(excel_file_path, sheet_name=sheet_name)
    print(f"Successfully read sheet '{sheet_name}' from '{excel_file_path}'.")
    print("First 5 rows of the DataFrame:")
    print(df_tf.head())
except FileNotFoundError:
    print(f"Error: The file '{excel_file_path}' was not found. Please check the path.")
except ValueError as e:
    print(f"Error reading sheet '{sheet_name}': {e}. Please ensure the sheet name is correct.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

Successfully read sheet 'TRANSFERAN' from '/content/gdrive/MyDrive/Data_Keuangan/Laporan kasir.xlsx'.
First 5 rows of the DataFrame:
  Data Pembayaran Transfer           Unnamed: 1       Unnamed: 2  Unnamed: 3  \
0      2026-05-01 00:00:00                  NaN              NaN         NaN
1                       No    Tanggal Transaksi      Nama Pasien        ASAL
2                      NaN                  NaN              NaN  Poli OBGYN
3                        1  2026-05-01 00:00:00        NURHAYATI      783932
4                        2                  NaN  LIDYA AGUSTIN        242039

  Unnamed: 4 Unnamed: 5 Unnamed: 6        Unnamed: 7  Unnamed: 8 Unnamed: 9  \
0        NaN        NaN        NaN               NaN         NaN        NaN
1        NaN        NaN        NaN               NaN         NaN        NaN
2   Poli DVE  Poli Anak        IGD  Ranap IBU & Bayi  Ranap Anak    Lainnya
3        NaN        NaN        NaN               NaN         NaN        NaN
4        NaN        NaN        NaN               NaN         NaN        NaN

  Unnamed: 10
0         NaN
1         KET
2         NaN
3         NaN
4         NaN

In [ ]:
df_tf.head()

,Data Pembayaran Transfer,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,2026-05-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,No,Tanggal Transaksi,Nama Pasien,ASAL,NaN,NaN,NaN,NaN,NaN,NaN,KET
2,NaN,NaN,NaN,Poli OBGYN,Poli DVE,Poli Anak,IGD,Ranap IBU & Bayi,Ranap Anak,Lainnya,NaN
3,1,2026-05-01 00:00:00,NURHAYATI,783932,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2,NaN,LIDYA AGUSTIN,242039,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_tf.tail()

,Data Pembayaran Transfer,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
112,110,NaN,INDAH PURNAMA SARI,250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113,111,2026-05-30 00:00:00,DELLA RAHMA DANI,305012,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,112,2026-05-31 00:00:00,BAMA YULIA AFNIKA,NaN,NaN,NaN,NaN,10000000,NaN,NaN,NaN
115,TOTAL,NaN,112 PASIEN,23923347,898259,3528865,553343,30505979,4277342,7730130,NaN
116,NaN,NaN,NaN,71417265,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_tf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117 entries, 0 to 116
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Data Pembayaran Transfer  115 non-null    object
 1   Unnamed: 1                28 non-null     object
 2   Unnamed: 2                114 non-null    object
 3   Unnamed: 3                76 non-null     object
 4   Unnamed: 4                6 non-null      object
 5   Unnamed: 5                14 non-null     object
 6   Unnamed: 6                5 non-null      object
 7   Unnamed: 7                9 non-null      object
 8   Unnamed: 8                3 non-null      object
 9   Unnamed: 9                15 non-null     object
 10  Unnamed: 10               14 non-null     object
dtypes: object(11)
memory usage: 10.2+ KB

## Data Closingan

In [ ]:
# Define the path to your Excel file
excel_file_path = '/content/gdrive/MyDrive/Data_Keuangan/data sistem 1 - 31 mei.xlsx'

# Define the name of the sheet you want to read
sheet_name = 'PendapatanPerAkunClosing'  # e.g., 'Sheet2', 'My Data'

try:
    # Read the specified sheet from the Excel file into a DataFrame
    df_cl = pd.read_excel(excel_file_path, sheet_name=sheet_name)
    print(f"Successfully read sheet '{sheet_name}' from '{excel_file_path}'.")
    print("First 5 rows of the DataFrame:")
    print(df_cl.head())
except FileNotFoundError:
    print(f"Error: The file '{excel_file_path}' was not found. Please check the path.")
except ValueError as e:
    print(f"Error reading sheet '{sheet_name}': {e}. Please ensure the sheet name is correct.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

Successfully read sheet 'PendapatanPerAkunClosing' from '/content/gdrive/MyDrive/Data_Keuangan/data sistem 1 - 31 mei.xlsx'.
First 5 rows of the DataFrame:
   No.              Tanggal   No.Rawat/No.Nota               Nama Pasien  \
0  1.0  2026-05-01 00:00:00  2026/05/01/RJ0002       NY. NAILIL HIDAYATI
1  2.0  2026-05-01 00:00:00  2026/05/01/RJ0003          NY.FITRI SAKINAH
2  3.0  2026-05-01 00:00:00  2026/05/01/RJ0004  AN. GHESAN AHMAD ATHALLA
3  4.0  2026-05-01 00:00:00  2026/05/01/RJ0005              NY. FERAWATI
4  5.0  2026-05-01 00:00:00  2026/05/01/RJ0006     NY. RATNA AYU LESTARI

  Jenis/Cara Bayar   Akun Closing  Unnamed: 6
0             UMUM  1. Bayar Cash    150000.0
1             UMUM  1. Bayar Cash    300827.0
2             UMUM  1. Bayar Cash    421045.0
3             UMUM  1. Bayar Cash    182920.0
4             UMUM  1. Bayar Cash    150000.0

In [ ]:
df_cl.tail()

,No.,Tanggal,No.Rawat/No.Nota,Nama Pasien,Jenis/Cara Bayar,Akun Closing,Unnamed: 6
1265,NaN,Total 2. Piutang BPJS,NaN,NaN,NaN,1064643829,NaN
1266,NaN,Total 3. Piutang Umum Rawat Inap,NaN,NaN,NaN,135802,NaN
1267,NaN,Total 4. Piutang Ad Medika,NaN,NaN,NaN,15002895,NaN
1268,NaN,Total PIUTANG OBAT & BHP,NaN,NaN,NaN,4011642,NaN
1269,NaN,Jumlah Total,NaN,NaN,NaN,1250254327,NaN

In [ ]:
df_cl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1270 entries, 0 to 1269
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   No.               1253 non-null   float64
 1   Tanggal           1263 non-null   object
 2   No.Rawat/No.Nota  1253 non-null   object
 3   Nama Pasien       1253 non-null   object
 4   Jenis/Cara Bayar  1253 non-null   object
 5   Akun Closing      1263 non-null   object
 6   Unnamed: 6        1253 non-null   float64
dtypes: float64(2), object(5)
memory usage: 69.6+ KB

## Data Arus Kas

In [ ]:
# Define the path to your Excel file
excel_file_path = '/content/gdrive/MyDrive/Data_Keuangan/ARUS KAS 2026.xlsx'

# Define the name of the sheet you want to read
sheet_name = 'Mei'  # e.g., 'Sheet2', 'My Data'

try:
    # Read the specified sheet from the Excel file into a DataFrame
    df_ak = pd.read_excel(excel_file_path, sheet_name=sheet_name)
    print(f"Successfully read sheet '{sheet_name}' from '{excel_file_path}'.")
    print("First 5 rows of the DataFrame:")
    print(df_ak.head())
except FileNotFoundError:
    print(f"Error: The file '{excel_file_path}' was not found. Please check the path.")
except ValueError as e:
    print(f"Error reading sheet '{sheet_name}': {e}. Please ensure the sheet name is correct.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

Successfully read sheet 'Mei' from '/content/gdrive/MyDrive/Data_Keuangan/ARUS KAS 2026.xlsx'.
First 5 rows of the DataFrame:
   No.  Tanggal Buku Tanggal Transaksi  Kode Akun  \
0  NaN           NaN               NaN        NaN
1  NaN           NaN               NaN        NaN
2  NaN           NaN         01-May-26        NaN
3  NaN           NaN         01-May-26        NaN
4  NaN           NaN         01-May-26        NaN

                           KETERANGAN  Unnamed: 5      CASH Unnamed: 7  \
0                                 NaN         NaN     Debit     Kredit
1               Saldo Awal 1 Mei 2026         NaN  14853377        NaN
2      Obat Bebas Apotik TGL 30 APRIL     93000.0       NaN        NaN
3         Penjualan Toko Korset 1 pcs     60000.0       NaN        NaN
4  Rajal IGD a/n GHESAN AHMAD ATHALLA    421000.0       NaN        NaN

        Saldo      GIRO Unnamed: 10     Saldo.1 Tanggal Transaksi.1  \
0         NaN     Debit      Kredit         NaN                 NaN
1  14853377.0  16543417         NaN  16543417.0  Saldo per 1/5/2026
2  14853377.0       NaN         NaN  16543417.0                 NaN
3  14853377.0       NaN         NaN  16543417.0                 NaN
4  14853377.0       NaN         NaN  16543417.0                 NaN

  BISNIS UMUM Unnamed: 14       SALDO
0       DEBIT      KREDIT         NaN
1    97404953         NaN  97404953.0
2         NaN         NaN  97404953.0
3         NaN         NaN  97404953.0
4         NaN         NaN  97404953.0

In [ ]:
df_ak.tail()

,No.,Tanggal Buku,Tanggal Transaksi,Kode Akun,KETERANGAN,Unnamed: 5,CASH,Unnamed: 7,Saldo,GIRO,Unnamed: 10,Saldo.1,Tanggal Transaksi.1,BISNIS UMUM,Unnamed: 14,SALDO
907,NaN,NaN,31-May-26,NaN,Penjualan Toko Korset 1 Pcs,60000.0,NaN,NaN,2910640.0,NaN,NaN,75340235.0,NaN,NaN,NaN,162485056.0
908,NaN,NaN,31-May-26,NaN,Penjualan Toko Pompa Asi menengah,136000.0,NaN,NaN,2910640.0,NaN,NaN,75340235.0,NaN,NaN,NaN,162485056.0
909,NaN,NaN,31-May-26,NaN,Obat Bebas Apotik 31 Mei 2026,129000.0,NaN,NaN,2910640.0,NaN,NaN,75340235.0,NaN,NaN,NaN,162485056.0
910,NaN,NaN,NaN,NaN,Pendapatan 31/5,15402500.0,NaN,NaN,2910640.0,NaN,NaN,75340235.0,NaN,NaN,NaN,162485056.0
911,TOTAL,NaN,NaN,NaN,NaN,NaN,429742997,426832357,NaN,562032783,486692548,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_ak.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 912 entries, 0 to 911
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   No.                  1 non-null      object
 1   Tanggal Buku         0 non-null      float64
 2   Tanggal Transaksi    877 non-null    object
 3   Kode Akun            343 non-null    float64
 4   KETERANGAN           910 non-null    object
 5   Unnamed: 5           534 non-null    float64
 6   CASH                 25 non-null     object
 7   Unnamed: 7           250 non-null    object
 8   Saldo                910 non-null    float64
 9   GIRO                 9 non-null      object
 10  Unnamed: 10          108 non-null    object
 11  Saldo.1              910 non-null    float64
 12  Tanggal Transaksi.1  1 non-null      object
 13  BISNIS UMUM          104 non-null    object
 14  Unnamed: 14          1 non-null      object
 15  SALDO                910 non-null    float64
dtypes: float64(6), object(10)
memory usage: 114.1+ KB

# **5. Data Preprocessing**

Pada tahap ini, data preprocessing adalah langkah penting untuk memastikan kualitas data sebelum digunakan dalam model machine learning.

Jika Anda menggunakan data teks, data mentah sering kali mengandung nilai kosong, duplikasi, atau rentang nilai yang tidak konsisten, yang dapat memengaruhi kinerja model. Oleh karena itu, proses ini bertujuan untuk membersihkan dan mempersiapkan data agar analisis berjalan optimal.

Berikut adalah tahapan-tahapan yang bisa dilakukan, tetapi **tidak terbatas** pada:
1. Menghapus atau Menangani Data Kosong (Missing Values)
2. Menghapus Data Duplikat
3. Normalisasi atau Standarisasi Fitur
4. Deteksi dan Penanganan Outlier
5. Encoding Data Kategorikal
6. Binning (Pengelompokan Data)

Cukup sesuaikan dengan karakteristik data yang kamu gunakan yah. Khususnya ketika kami menggunakan data tidak terstruktur.

## Data TO

In [ ]:
# Remove the current first row (index 0) as it's not a header
df_to = df_to.iloc[1:].reset_index(drop=True)

# The row containing 'TGL', 'NO', 'NAMA PASIEN' is now at index 1
# Use this row as the new column headers
df_to.columns = df_to.iloc[1]

# Remove the rows that are not actual data:
# - The row that was used as the new header (now at index 1)
# - The row immediately below it (now at index 2) which appears to be sub-header information
# - The row at index 0 which contains a date and is not part of the data
# So, keep rows starting from index 3 (which contains the first actual data entry)
df_to = df_to.iloc[3:].reset_index(drop=True)

In [ ]:
# Define the new, corrected column names based on the original Excel structure
new_column_names = [
    'Tanggal',
    'No',
    'Nama Pasien',
    'Konsul',
    'Adm',
    'USG (2/4) D',
    'T.Verban',
    'Injeksi',
    'USG V',
    'Total'
]

# Check if the number of new column names matches the number of columns in the DataFrame
if len(new_column_names) == len(df_to.columns):
    # Assign the new column names to the DataFrame
    df_to.columns = new_column_names
    print("Column names updated successfully.")
    print("First 5 rows with new headers:")
    print(df_to.head())
else:
    print(f"Error: Number of new column names ({len(new_column_names)}) does not match "
          f"the number of existing columns ({len(df_to.columns)}). Please adjust the `new_column_names` list.")

Column names updated successfully.
First 5 rows with new headers:
               Tanggal No         Nama Pasien Konsul    Adm USG (2/4) D  \
0  2026-05-01 00:00:00  1   RATNA AYU LESTARI  90000  20000       40000
1                  NaN  2        MEGA EMELIA   90000  20000      140000
2                  NaN  3  JIHAN DELLA ANANDA  90000  20000      140000
3                  NaN  4  ROZA MELIA AFRIANA  90000  20000       40000
4                  NaN  5    KESSY RAMA DILLA  90000  20000       40000

  T.Verban Injeksi USG V   Total
0      NaN     NaN   NaN  150000
1      NaN     NaN   NaN  250000
2      NaN     NaN   NaN  250000
3      NaN     NaN   NaN  150000
4      NaN     NaN   NaN  150000

In [ ]:
# Select only the desired columns
df_to = df_to[['Tanggal', 'Nama Pasien', 'Total']].copy()

# Convert 'Tanggal' column to datetime, coercing errors to NaT
df_to['Tanggal'] = pd.to_datetime(df_to['Tanggal'], errors='coerce')

# Format the 'Tanggal' column to 'DD-MM-YYYY' string format
df_to['Tanggal'] = df_to['Tanggal'].dt.strftime('%d-%m-%Y')

In [ ]:
# Fill NaN values in 'Tanggal' column with the previous valid date
df_to['Tanggal'] = df_to['Tanggal'].ffill()

/tmp/ipykernel_1569/4261319843.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_to['Tanggal'] = df_to['Tanggal'].fillna(method='ffill')

In [ ]:
# Remove rows where 'Nama Pasien' or 'Total' is NaN
df_to = df_to.dropna(subset=['Nama Pasien', 'Total'])

# Rename the 'Total' column to 'Nominal'
df_to = df_to.rename(columns={'Total': 'Nominal'})

print("DataFrame after removing NaN rows and renaming 'Total' to 'Nominal':")
print(df_to.head())
print("\nInfo DataFrame setelah pembersihan:")
df_to.info()

DataFrame after removing NaN rows and renaming 'Total' to 'Nominal':
      Tanggal         Nama Pasien Nominal
0  01-05-2026   RATNA AYU LESTARI  150000
1  01-05-2026        MEGA EMELIA   250000
2  01-05-2026  JIHAN DELLA ANANDA  250000
3  01-05-2026  ROZA MELIA AFRIANA  150000
4  01-05-2026    KESSY RAMA DILLA  150000

Info DataFrame setelah pembersihan:
<class 'pandas.core.frame.DataFrame'>
Index: 82 entries, 0 to 81
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Tanggal      82 non-null     object
 1   Nama Pasien  82 non-null     object
 2   Nominal      82 non-null     object
dtypes: object(3)
memory usage: 2.6+ KB

In [ ]:
df_to.tail()

       Tanggal          Nama Pasien Nominal
77  29-05-2026  LINDA SYOFIA MELATI  150000
78  29-05-2026     LAHYA RAMA FITRI  150000
79  29-05-2026            FATMAWATI  250000
80  29-05-2026      AULIA RAHMADANI  150000
81  29-05-2026                YANTI  250000

## Data Transfer

In [ ]:
# Define the new, corrected column names as requested by the user
new_column_names = [
    'No',
    'Tanggal Transaksi',
    'Nama Pasien',
    'Poli OBGYN',
    'Poli DVE',
    'Poli Anak',
    'IGD',
    'Ranap IBU & Bayi',
    'Ranap Anak',
    'Lainnya',
    'KET'
]

# Ensure the number of new column names matches the current number of columns
if len(new_column_names) == len(df_tf.columns):
    # Set the new column names
    df_tf.columns = new_column_names

    # Drop the first 3 rows, which contained the old header structure
    df_tf = df_tf.iloc[3:].reset_index(drop=True)

    print("DataFrame after updating headers and removing initial rows:")
    print(df_tf.head())
else:
    print(f"Error: Jumlah nama kolom baru ({len(new_column_names)}) tidak sesuai "
          f"dengan jumlah kolom yang ada ({len(df_tf.columns)}). Mohon sesuaikan daftar `new_column_names`.")

DataFrame after updating headers and removing initial rows:
  No    Tanggal Transaksi              Nama Pasien Poli OBGYN Poli DVE  \
0  1  2026-05-01 00:00:00                NURHAYATI     783932      NaN
1  2                  NaN          LIDYA AGUSTIN       242039      NaN
2  3  2026-05-02 00:00:00  ELVARA ARTHA APRYXELLE         NaN      NaN
3  4                  NaN             AMIA LUGITA      150000      NaN
4  5                  NaN        ZAKIAH TUSSYIANI      150000      NaN

  Poli Anak  IGD Ranap IBU & Bayi Ranap Anak Lainnya         KET
0       NaN  NaN              NaN        NaN     NaN         NaN
1       NaN  NaN              NaN        NaN     NaN         NaN
2       NaN  NaN              NaN        NaN   35000  Imunisasi
3       NaN  NaN              NaN        NaN     NaN         NaN
4       NaN  NaN              NaN        NaN     NaN         NaN

In [ ]:
# 1. Hapus kolom 'No' dan 'KET'
df_tf = df_tf.drop(columns=['No', 'KET'])

# Kolom-kolom yang akan diakumulasikan untuk 'Nominal'
nominal_columns = [
    'Poli OBGYN',
    'Poli DVE',
    'Poli Anak',
    'IGD',
    'Ranap IBU & Bayi',
    'Ranap Anak',
    'Lainnya'
]

# Konversi kolom-kolom numerik ke tipe data numerik, ganti NaN dengan 0 untuk penjumlahan
for col in nominal_columns:
    df_tf[col] = pd.to_numeric(df_tf[col], errors='coerce').fillna(0)

# 2. Tambahkan kolom 'Nominal' yang diisi dengan akumulasi
df_tf['Nominal'] = df_tf[nominal_columns].sum(axis=1)

# 3. Hapus kolom-kolom yang sudah diakumulasikan
df_tf = df_tf.drop(columns=nominal_columns)

# 4. Ubah format tanggal 'Tanggal Transaksi' menjadi 'DD-MM-YYYY'
df_tf['Tanggal Transaksi'] = pd.to_datetime(df_tf['Tanggal Transaksi'], errors='coerce')
df_tf['Tanggal Transaksi'] = df_tf['Tanggal Transaksi'].dt.strftime('%d-%m-%Y')

print("DataFrame setelah pemrosesan:")
print(df_tf.head())
print("\nInfo DataFrame setelah pembersihan:")
df_tf.info()

DataFrame setelah pemrosesan:
  Tanggal Transaksi              Nama Pasien   Nominal
0        01-05-2026                NURHAYATI  783932.0
1               NaN          LIDYA AGUSTIN    242039.0
2        02-05-2026  ELVARA ARTHA APRYXELLE    35000.0
3               NaN             AMIA LUGITA   150000.0
4               NaN        ZAKIAH TUSSYIANI   150000.0

Info DataFrame setelah pembersihan:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114 entries, 0 to 113
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Tanggal Transaksi  27 non-null     object
 1   Nama Pasien        113 non-null    object
 2   Nominal            114 non-null    float64
dtypes: float64(1), object(2)
memory usage: 2.8+ KB

In [ ]:
# 1. Hapus dua baris terakhir
df_tf = df_tf.iloc[:-2].copy()

# 2. Isi baris NaN pada kolom 'Tanggal Transaksi' dengan data tanggal baris sebelumnya
df_tf['Tanggal Transaksi'] = df_tf['Tanggal Transaksi'].ffill()

# 3. Ubah format 'Nominal' dari float menjadi integer
df_tf['Nominal'] = df_tf['Nominal'].astype(int)

/tmp/ipykernel_1569/4015508828.py:5: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_tf['Tanggal Transaksi'] = df_tf['Tanggal Transaksi'].fillna(method='ffill')

In [ ]:
df_tf = df_tf.rename(columns={'Tanggal Transaksi': 'Tanggal'})

print("DataFrame after renaming 'Tanggal Transaksi' to 'Tanggal':")
print(df_tf.head())
print("\nInfo DataFrame setelah perubahan nama kolom:")
df_tf.info()

DataFrame after renaming 'Tanggal Transaksi' to 'Tanggal':
      Tanggal              Nama Pasien  Nominal
0  01-05-2026                NURHAYATI   783932
1  01-05-2026          LIDYA AGUSTIN     242039
2  02-05-2026  ELVARA ARTHA APRYXELLE     35000
3  02-05-2026             AMIA LUGITA    150000
4  02-05-2026        ZAKIAH TUSSYIANI    150000

Info DataFrame setelah perubahan nama kolom:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112 entries, 0 to 111
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Tanggal      112 non-null    object
 1   Nama Pasien  112 non-null    object
 2   Nominal      112 non-null    int64
dtypes: int64(1), object(2)
memory usage: 2.8+ KB

In [ ]:
df_tf.tail()

        Tanggal          Nama Pasien   Nominal
107  29-05-2026  C. MERRY KUSUMAWATI    176163
108  29-05-2026       NAZHIFAH RAHMI    523222
109  29-05-2026   INDAH PURNAMA SARI    250000
110  30-05-2026    DELLA RAHMA DANI     305012
111  31-05-2026    BAMA YULIA AFNIKA  10000000

## Data Closingan

In [ ]:
# 1. Ubah nama kolom 'Unnamed: 6' menjadi 'NOMINAL'
df_cl = df_cl.rename(columns={'Unnamed: 6': 'NOMINAL'})

# 2. Hapus kolom 'No.' dan 'No.Rawat/No.Nota'
df_cl = df_cl.drop(columns=['No.', 'No.Rawat/No.Nota'])

# 3. Ganti format tanggal '2026-05-14 00:00:00' menjadi '14-05-2026'
# Pastikan kolom 'Tanggal' adalah tipe datetime terlebih dahulu
df_cl['Tanggal'] = pd.to_datetime(df_cl['Tanggal'], errors='coerce')
df_cl['Tanggal'] = df_cl['Tanggal'].dt.strftime('%d-%m-%Y')

# 4. Hapus 4 baris terakhir
df_cl = df_cl.iloc[:-10]

# 5. Isi baris yang mengandung nilai NaN dengan isian dari baris sebelumnya (forward fill)
df_cl = df_cl.ffill()

In [ ]:
import re

def clean_keterangan(text):
    if pd.isna(text):
        return text
    text_str = str(text)
    # Check if the text starts with 'by.', 'BY.', or 'By.' (case-insensitive)
    if re.match(r'^(by\.)\s+', text_str, re.IGNORECASE):
        return text_str
    # Otherwise, remove 'ny.', 'An.', 'Tn.', 'NN.' at the beginning, optionally followed by spaces
    return re.sub(r'^(ny\.|an\.|tn\.|nn\.)\s*', '', text_str, flags=re.IGNORECASE)

df_cl['Nama Pasien'] = df_cl['Nama Pasien'].apply(clean_keterangan)

# Display the head of the DataFrame to show the changes
print("DataFrame after cleaning Nama Pasiencolumn:")
print(df_cl.head())

DataFrame after cleaning Nama Pasiencolumn:
      Tanggal           Nama Pasien Jenis/Cara Bayar   Akun Closing   NOMINAL
0  01-05-2026       NAILIL HIDAYATI             UMUM  1. Bayar Cash  150000.0
1  01-05-2026         FITRI SAKINAH             UMUM  1. Bayar Cash  300827.0
2  01-05-2026  GHESAN AHMAD ATHALLA             UMUM  1. Bayar Cash  421045.0
3  01-05-2026              FERAWATI             UMUM  1. Bayar Cash  182920.0
4  01-05-2026     RATNA AYU LESTARI             UMUM  1. Bayar Cash  150000.0

In [ ]:
df_cl = df_cl[df_cl['Akun Closing'] != '2. Piutang BPJS']

In [ ]:
df_cl = df_cl[df_cl['Akun Closing'] != 'PIUTANG OBAT & BHP']

In [ ]:
df_cl = df_cl[df_cl['Nama Pasien'] != 'x']

In [ ]:
df_cl = df_cl[~df_cl['Jenis/Cara Bayar'].str.contains('Penjualan Apotek', na=False)]

In [ ]:
df_cl.head()

      Tanggal           Nama Pasien Jenis/Cara Bayar   Akun Closing   NOMINAL
0  01-05-2026       NAILIL HIDAYATI             UMUM  1. Bayar Cash  150000.0
1  01-05-2026         FITRI SAKINAH             UMUM  1. Bayar Cash  300827.0
2  01-05-2026  GHESAN AHMAD ATHALLA             UMUM  1. Bayar Cash  421045.0
3  01-05-2026              FERAWATI             UMUM  1. Bayar Cash  182920.0
4  01-05-2026     RATNA AYU LESTARI             UMUM  1. Bayar Cash  150000.0

## Data Arus Kas

In [ ]:
columns_to_drop = [
    'No.', 'Tanggal Buku', 'Kode Akun', 'CASH', 'Unnamed: 7', 'Saldo',
    'GIRO', 'Unnamed: 10', 'Saldo.1', 'Tanggal Transaksi.1', 'BISNIS UMUM',
    'Unnamed: 14', 'SALDO'
]

df_ak = df_ak.drop(columns=columns_to_drop)

In [ ]:
df_ak = df_ak.rename(columns={'Unnamed: 5': 'Nominal'})

In [ ]:
print(f"Shape of DataFrame before dropping empty rows: {df_ak.shape}")
df_cleaned = df_ak.dropna(how='all')
print(f"Shape of DataFrame after dropping empty rows: {df_cleaned.shape}")

df_ak = df_cleaned.copy()

Shape of DataFrame before dropping empty rows: (912, 3)
Shape of DataFrame after dropping empty rows: (910, 3)

In [ ]:
df_ak['Tanggal Transaksi'] = pd.to_datetime(df_ak['Tanggal Transaksi'], errors='coerce')
df_ak['Tanggal Transaksi'] = df_ak['Tanggal Transaksi'].dt.strftime('%d-%m-%Y').fillna('')

# Convert 'Nominal' column to integer, handling potential NaN values
df_ak['Nominal'] = pd.to_numeric(df_ak['Nominal'], errors='coerce').astype('Int64')

/tmp/ipykernel_1569/3957176455.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_ak['Tanggal Transaksi'] = pd.to_datetime(df_ak['Tanggal Transaksi'], errors='coerce')

In [ ]:
# Define a pattern to *identify* rows that are likely patient-related transactions.
# This pattern checks for the presence of any of the prefixes. Using '|' to match any of the keywords.
identification_pattern = r'a/n|Rajal Kebidanan|Rajal IGD|Poli Anak|Rajal DVE|Vaksin'

# Filter the DataFrame to keep only rows containing these patterns.
# Ensure 'KETERANGAN' column is string type before applying string methods.
df_pasien = df_ak[df_ak['KETERANGAN'].astype(str).str.contains(
    identification_pattern, case=False, na=False
)].copy()

# Define a pattern to *remove* the prefixes from the KETERANGAN column.
# This pattern matches any of the prefixes (including 'a/n' with an optional dot)
# followed by zero or more spaces. The non-capturing group (?:...) ensures
# we match these prefixes without capturing them as part of the desired name.
# The `.` is escaped to match a literal dot, and `?` makes it optional. `\s*` matches any whitespace.
removal_pattern = r'(?:a/n\\.?|Rajal Kebidanan|Rajal IGD|Poli Anak|Rajal DVE|Vaksin)\s*'

# Apply the removal pattern to clean the 'KETERANGAN' column.
# re.sub replaces all occurrences of the pattern. Then, strip any remaining leading/trailing whitespace.
df_pasien['KETERANGAN'] = df_pasien['KETERANGAN'].astype(str).apply(
    lambda x: re.sub(removal_pattern, '', x, flags=re.IGNORECASE).strip()
)

# Remove rows where KETERANGAN might have become empty after cleaning all prefixes
df_pasien = df_pasien[df_pasien['KETERANGAN'] != '']

# Pilih kolom yang diperlukan
hasil = df_pasien[
    ['Tanggal Transaksi', 'KETERANGAN', 'Nominal']
].copy()

hasil.columns = [
    'Tanggal Transaksi',
    'Keterangan',
    'Nominal'
]

print(hasil)

    Tanggal Transaksi                            Keterangan  Nominal
4          01-05-2026              a/n GHESAN AHMAD ATHALLA   421000
5          01-05-2026                   a/n NAILIL HIDAYATI   150000
6          01-05-2026                     a/n FITRI SAKINAH   301000
7          01-05-2026                          a/n FERAWATI   183000
8          01-05-2026                  a/n ERJA WHULAN SARI   256000
..                ...                                   ...      ...
902        31-05-2026  Ranap Umum a/n By. BAMA YULIA AFNIKA  1240000
903        31-05-2026                a/n NAYELA ARESA ZEEYA   114500
904        31-05-2026                  a/n NAYEL ARESA ZEAN   245000
905        31-05-2026               a/n ALSYAKI DARYA ARFAN    77000
906        31-05-2026               a/n QISTY HUMAIRA DELIA    98500

[434 rows x 3 columns]

In [ ]:
df_ak=hasil.copy()
df_ak.head()

  Tanggal Transaksi                Keterangan  Nominal
4        01-05-2026  a/n GHESAN AHMAD ATHALLA   421000
5        01-05-2026       a/n NAILIL HIDAYATI   150000
6        01-05-2026         a/n FITRI SAKINAH   301000
7        01-05-2026              a/n FERAWATI   183000
8        01-05-2026      a/n ERJA WHULAN SARI   256000

In [ ]:
def clean_keterangan(text):
    if pd.isna(text):
        return text

    text = str(text).strip()

    removal_regex = (
        r'^(?:'
        r'Ranap Naik Kelas\s*|'
        r'laboratorium\s*|'
        r'Imunisasi\s*|'
        r'Ranap Umum\s*|'
        r'Poli Bedah\s*|'
        r'Poli Kulit\s*|'
        r'a\s*/\s*n\.?\s*|'
        r'ny\.?(?=\s|[A-Z]|$)\s*|'
        r'tn\.?(?=\s|[A-Z]|$)\s*|'
        r'an\.?(?=\s)\s*'
        r')+'
    )

    return re.sub(removal_regex, '', text, flags=re.IGNORECASE).strip()

df_ak['Keterangan'] = df_ak['Keterangan'].apply(clean_keterangan)

In [ ]:
df_ak = df_ak.rename(columns={'Tanggal Transaksi': 'Tanggal', 'Keterangan': 'Nama Pasien'})
df_ak.head()

      Tanggal           Nama Pasien  Nominal
4  01-05-2026  GHESAN AHMAD ATHALLA   421000
5  01-05-2026       NAILIL HIDAYATI   150000
6  01-05-2026         FITRI SAKINAH   301000
7  01-05-2026              FERAWATI   183000
8  01-05-2026      ERJA WHULAN SARI   256000

## Gabungan Data TO, Transfer, Arus Kas dan Closingan

In [ ]:
df_ak.head()

      Tanggal           Nama Pasien  Nominal
4  01-05-2026  GHESAN AHMAD ATHALLA   421000
5  01-05-2026       NAILIL HIDAYATI   150000
6  01-05-2026         FITRI SAKINAH   301000
7  01-05-2026              FERAWATI   183000
8  01-05-2026      ERJA WHULAN SARI   256000

In [ ]:
df_cl.head()

      Tanggal           Nama Pasien Jenis/Cara Bayar   Akun Closing   NOMINAL
0  01-05-2026       NAILIL HIDAYATI             UMUM  1. Bayar Cash  150000.0
1  01-05-2026         FITRI SAKINAH             UMUM  1. Bayar Cash  300827.0
2  01-05-2026  GHESAN AHMAD ATHALLA             UMUM  1. Bayar Cash  421045.0
3  01-05-2026              FERAWATI             UMUM  1. Bayar Cash  182920.0
4  01-05-2026     RATNA AYU LESTARI             UMUM  1. Bayar Cash  150000.0

In [ ]:
df_to.head()

      Tanggal         Nama Pasien Nominal
0  01-05-2026   RATNA AYU LESTARI  150000
1  01-05-2026        MEGA EMELIA   250000
2  01-05-2026  JIHAN DELLA ANANDA  250000
3  01-05-2026  ROZA MELIA AFRIANA  150000
4  01-05-2026    KESSY RAMA DILLA  150000

In [ ]:
df_tf.head()

      Tanggal              Nama Pasien  Nominal
0  01-05-2026                NURHAYATI   783932
1  01-05-2026          LIDYA AGUSTIN     242039
2  02-05-2026  ELVARA ARTHA APRYXELLE     35000
3  02-05-2026             AMIA LUGITA    150000
4  02-05-2026        ZAKIAH TUSSYIANI    150000

In [ ]:
import pandas as pd
import numpy as np
import difflib
import re
from IPython.display import display

# 0. FUNGSI BANTUAN: FUZZY NAME MATCHING
def cek_kemiripan_nama(n1, n2):
    """
    Fungsi untuk mendeteksi apakah 2 nama adalah orang yang sama.
    Contoh True: "M. ARVAN" vs "MUHAMMAD ARVAN"
    """
    if pd.isna(n1) or pd.isna(n2): return False

    n1_clean = re.sub(r'[^A-Z\s]', '', str(n1).upper()).strip()
    n2_clean = re.sub(r'[^A-Z\s]', '', str(n2).upper()).strip()

    if n1_clean == n2_clean: return True

    # Rule 1: Rasio kemiripan karakter > 80%
    if difflib.SequenceMatcher(None, n1_clean, n2_clean).ratio() > 0.8:
        return True

    # Rule 2: Cek Singkatan / Inisial (Syarat: Huruf pertama sama & ada irisan nama belakang)
    if n1_clean and n2_clean and n1_clean[0] == n2_clean[0]:
        tok1 = set([t for t in n1_clean.split() if len(t) > 2]) # Ambil kata > 2 huruf
        tok2 = set([t for t in n2_clean.split() if len(t) > 2])
        if tok1.intersection(tok2): # Jika "ARVAN" ada di kedua nama
            return True

    return False

# 1. PREPROCESSING & CLEANING DATA
df_cl = df_cl.rename(columns={'NOMINAL': 'Nominal CL', 'Jenis/Cara Bayar': 'Jenis Bayar'})
df_ak = df_ak.rename(columns={'Nominal': 'Nominal AK'})
df_tf = df_tf.rename(columns={'Nominal': 'Nominal TF'})
df_to = df_to.rename(columns={'Nominal': 'Nominal TO'})

if 'Akun Closing' not in df_cl.columns:
    df_cl['Akun Closing'] = 'UNKNOWN'

for df in [df_cl, df_ak, df_tf, df_to]:
    df['Tanggal'] = pd.to_datetime(df['Tanggal'], dayfirst=True)
    df['Nama Pasien'] = df['Nama Pasien'].astype(str).str.upper().str.strip()

df_cl['Jenis Bayar'] = df_cl['Jenis Bayar'].astype(str).str.upper().str.strip()
df_cl['Akun Closing'] = df_cl['Akun Closing'].astype(str).str.upper().str.strip()

df_cl['Nominal CL'] = pd.to_numeric(df_cl['Nominal CL'], errors='coerce')
df_ak['Nominal AK'] = pd.to_numeric(df_ak['Nominal AK'], errors='coerce')
df_tf['Nominal TF'] = pd.to_numeric(df_tf['Nominal TF'], errors='coerce')
df_to['Nominal TO'] = pd.to_numeric(df_to['Nominal TO'], errors='coerce')

# 2. PROSES FUZZY MATCHING NAMA PASIEN
# Menyinkronkan nama "M. Arvan" di mutasi agar sama persis dengan "Muhammad Arvan" di Closing
dict_cl_names = df_cl.groupby('Tanggal')['Nama Pasien'].apply(list).to_dict()

for df_mutasi in [df_ak, df_tf, df_to]:
    for idx, row in df_mutasi.iterrows():
        tgl = row['Tanggal']
        nama_mutasi = row['Nama Pasien']

        if tgl in dict_cl_names:
            for nama_closing in dict_cl_names[tgl]:
                # Jika nama mirip secara logika fuzzy, timpa nama mutasi dengan nama closing
                if cek_kemiripan_nama(nama_mutasi, nama_closing):
                    df_mutasi.at[idx, 'Nama Pasien'] = nama_closing
                    break

# 3. GLOBAL LOOKUP (CROSS-DATE CHECKING)
dict_cl_dates = df_cl.groupby('Nama Pasien')['Tanggal'].apply(set).to_dict()
df_all_mutasi = pd.concat([df_ak[['Tanggal', 'Nama Pasien']], df_tf[['Tanggal', 'Nama Pasien']], df_to[['Tanggal', 'Nama Pasien']]]).drop_duplicates()
dict_mutasi_dates = df_all_mutasi.groupby('Nama Pasien')['Tanggal'].apply(set).to_dict()

# 4. MERGING DATA
audit_df = pd.merge(df_cl, df_ak[['Tanggal', 'Nama Pasien', 'Nominal AK']], on=['Tanggal', 'Nama Pasien'], how='outer')
audit_df = pd.merge(audit_df, df_tf[['Tanggal', 'Nama Pasien', 'Nominal TF']], on=['Tanggal', 'Nama Pasien'], how='outer')
audit_df = pd.merge(audit_df, df_to[['Tanggal', 'Nama Pasien', 'Nominal TO']], on=['Tanggal', 'Nama Pasien'], how='outer')

# 5. FIXED: PENANGANAN NaN SECARA AMAN
# Isi NaN dengan 0 SETELAH outer merge untuk menghindari ValueError
for col in ['Nominal CL', 'Nominal AK', 'Nominal TF', 'Nominal TO']:
    audit_df[col] = audit_df[col].fillna(0)

# Gunakan np.where() yang kebal terhadap tipe data NA / Float
audit_df['Exist_CL'] = np.where(audit_df['Nominal CL'] > 0, 1, 0)
audit_df['Exist_AK'] = np.where(audit_df['Nominal AK'] > 0, 1, 0)
audit_df['Exist_TF'] = np.where(audit_df['Nominal TF'] > 0, 1, 0)
audit_df['Exist_TO'] = np.where(audit_df['Nominal TO'] > 0, 1, 0)

audit_df['Jumlah_Titik_Mutasi'] = audit_df['Exist_AK'] + audit_df['Exist_TF'] + audit_df['Exist_TO']

# Imputasi Jenis Bayar
audit_df['Jenis Bayar'] = audit_df['Jenis Bayar'].replace(['NAN', 'NONE', 'NULL'], '')
audit_df['Jenis Bayar'] = audit_df['Jenis Bayar'].fillna('')
audit_df.loc[(audit_df['Jenis Bayar'] == '') & (audit_df['Exist_TF'] == 1), 'Jenis Bayar'] = 'TRANSFER'
audit_df.loc[(audit_df['Jenis Bayar'] == '') & (audit_df['Exist_TO'] == 1), 'Jenis Bayar'] = 'TO'
audit_df.loc[(audit_df['Jenis Bayar'] == '') & (audit_df['Exist_AK'] == 1), 'Jenis Bayar'] = 'TUNAI'

audit_df['Total_Mutasi'] = audit_df['Nominal AK'] + audit_df['Nominal TF'] + audit_df['Nominal TO']
audit_df['Selisih_Final'] = audit_df['Nominal CL'] - audit_df['Total_Mutasi']

# 6. ADVANCED MULTI-CLASS LABELING
def assign_audit_label(row):
    nama = row['Nama Pasien']
    tgl = row['Tanggal']
    jb = str(row['Jenis Bayar']).upper()
    total_mutasi = row['Total_Mutasi']
    selisih = row['Selisih_Final']
    titik_mutasi = row['Jumlah_Titik_Mutasi']

    # --- RULE A: UNRECORDED ---
    if row['Exist_CL'] == 0:
        if nama in dict_cl_dates and any(d != tgl for d in dict_cl_dates[nama]):
            return 'Tanggal Closing Tidak Sesuai (Uang masuk, tapi Closing di tanggal beda)'

        if row['Exist_TF'] == 1: return 'Unrecorded: Uang Masuk TF, Tanpa Closing'
        if row['Exist_TO'] == 1: return 'Unrecorded: Uang Masuk TO, Tanpa Closing'
        if row['Exist_AK'] == 1: return 'Unrecorded: Uang Masuk Kasir, Tanpa Closing'
        return 'Unrecorded: Multi-Mutasi'

    # --- RULE B: FIKTIF / TELAT ---
    if titik_mutasi == 0:
        if nama in dict_mutasi_dates and any(d != tgl for d in dict_mutasi_dates[nama]):
            return 'Pasien Telat Closing / Tanggal Mutasi Tidak Sesuai'
        return 'Critical: Ada di Closing, Tidak ada di arus kas'

    # --- RULE C: FRAUD RISK ---
    if titik_mutasi == 1 and selisih == 0:
        if ('TRANS' in jb or 'TF' in jb) and row['Exist_TF'] == 0:
            return 'Fraud Risk: Klaim TF, tapi masuk kas lain'
        if 'TO' in jb and row['Exist_TO'] == 0:
            return 'Fraud Risk: Klaim TO, tapi masuk kas lain'
        if ('TUNAI' in jb or 'CASH' in jb) and row['Exist_AK'] == 0:
            return 'Fraud Risk: Klaim Tunai, tapi masuk kas lain'

    # --- RULE D: SPLIT PAYMENT ---
    if titik_mutasi > 1:
        if selisih == 0: return 'Match via Split Payment'
        elif selisih < 0: return 'Anomaly: Double Input'
        else: return 'Split Payment: Kurang Bayar'

    # --- RULE E: SELISIH NOMINAL ---
    if selisih > 0: return 'Kurang Bayar (Nominal CL > Mutasi)'
    if selisih < 0: return 'Lebih Bayar (Nominal CL < Mutasi)'

    return 'Cleared & Matched'

audit_df['Label_Kategori'] = audit_df.apply(assign_audit_label, axis=1)
audit_df['Target_ML'], unik_labels = pd.factorize(audit_df['Label_Kategori'])

# 7. FINALISASI DATASET
kolom_final = [
    'Tanggal', 'Nama Pasien', 'Jenis Bayar', 'Akun Closing',
    'Nominal CL', 'Nominal AK', 'Nominal TF', 'Nominal TO',
    'Total_Mutasi', 'Selisih_Final', 'Jumlah_Titik_Mutasi',
    'Label_Kategori', 'Target_ML'
]

kolom_tersedia = [col for col in kolom_final if col in audit_df.columns]
audit_df = audit_df[kolom_tersedia].sort_values(by=['Tanggal', 'Nama Pasien']).reset_index(drop=True)
# 8. REPORTING
print("=" * 80)
print("DISTRIBUSI LABEL AUDIT - WITH FUZZY NAME MATCHING")
print("=" * 80)
print(f"Total Data Terproses: {len(audit_df)} Baris\n")

distribusi = audit_df['Label_Kategori'].value_counts()
for label, count in distribusi.items():
    print(f"- {label.ljust(65)} : {count}")
print("=" * 80)

================================================================================
DISTRIBUSI LABEL AUDIT - WITH FUZZY NAME MATCHING
================================================================================
Total Data Terproses: 595 Baris

- Cleared & Matched                                                 : 165
- Lebih Bayar (Nominal CL < Mutasi)                                 : 117
- Anomaly: Double Input                                             : 99
- Kurang Bayar (Nominal CL > Mutasi)                                : 83
- Pasien Telat Closing / Tanggal Mutasi Tidak Sesuai                : 41
- Tanggal Closing Tidak Sesuai (Uang masuk, tapi Closing di tanggal beda) : 37
- Critical: Ada di Closing, Tidak ada di arus kas                   : 25
- Unrecorded: Uang Masuk TF, Tanpa Closing                          : 12
- Unrecorded: Uang Masuk Kasir, Tanpa Closing                       : 9
- Unrecorded: Multi-Mutasi                                          : 7
================================================================================

In [ ]:
audit_df.head()

,Tanggal,Nama Pasien,Jenis Bayar,Akun Closing,Nominal CL,Nominal AK,Nominal TF,Nominal TO,Total_Mutasi,Selisih_Final,Jumlah_Titik_Mutasi,Label_Kategori,Target_ML
0,2026-05-01,AFIFAH CEFRINA PUTRI,UMUM,1. BAYAR CASH,352020.0,352000,0.0,0.0,352000.0,20.0,1,Kurang Bayar (Nominal CL > Mutasi),0
1,2026-05-01,ALBIRRU MALIK IBRAHIM,UMUM,1. BAYAR CASH,254811.0,255000,0.0,0.0,255000.0,-189.0,1,Lebih Bayar (Nominal CL < Mutasi),1
2,2026-05-01,DITA NILAM SARI,UMUM,1. BAYAR CASH,150000.0,150000,0.0,0.0,150000.0,0.0,1,Cleared & Matched,2
3,2026-05-01,ERJA WHULAN SARI,UMUM,1. BAYAR CASH,225819.0,256000,0.0,0.0,256000.0,-30181.0,1,Lebih Bayar (Nominal CL < Mutasi),1
4,2026-05-01,FERAWATI,UMUM,1. BAYAR CASH,182920.0,183000,0.0,0.0,183000.0,-80.0,1,Lebih Bayar (Nominal CL < Mutasi),1

In [ ]:
# 1. Tentukan nama file dan lokasi penyimpanan
csv_output_path = '/content/hasil_gabungan_cl_ak.csv'
excel_output_path = '/content/hasil_gabungan_cl_ak.xlsx'

# 2. Simpan ke CSV
# index=False agar kolom index tidak ikut tersimpan
audit_df.to_csv(csv_output_path, index=False)
print(f"Data berhasil disimpan ke CSV: {csv_output_path}")

# 3. Simpan ke Excel
audit_df.to_excel(excel_output_path, index=False)
print(f"Data berhasil disimpan ke Excel: {excel_output_path}")

Data berhasil disimpan ke CSV: /content/hasil_gabungan_cl_ak.csv
Data berhasil disimpan ke Excel: /content/hasil_gabungan_cl_ak.xlsx

## 5.1 Finalisasi Preprocessing untuk Pemodelan Machine Learning

### 5.1.1 Pengecekan & Penanganan Missing Value serta Duplikat (Final)

In [ ]:
# ==========================================
# CEK & PENANGANAN MISSING VALUE + DATA DUPLIKAT (FINAL)
# ==========================================
print("Jumlah missing value per kolom SEBELUM penanganan:")
print(audit_df.isna().sum())

# Kolom identitas/kategorikal yang kosong diisi label eksplisit,
# bukan dihapus, karena baris ini tetap relevan untuk audit
audit_df['Nama Pasien'] = audit_df['Nama Pasien'].fillna('TIDAK DIKETAHUI')
audit_df['Jenis Bayar'] = audit_df['Jenis Bayar'].astype(str).replace(
    ['', 'nan', 'NAN', 'None', 'NONE'], np.nan
).fillna('TIDAK DIKETAHUI')
if 'Akun Closing' in audit_df.columns:
    audit_df['Akun Closing'] = audit_df['Akun Closing'].fillna('TIDAK DIKETAHUI')

# Kolom numerik dipastikan bertipe numerik dan NaN -> 0
# (0 valid secara bisnis: artinya transaksi tidak tercatat di sumber tsb)
kolom_numerik = ['Nominal CL', 'Nominal AK', 'Nominal TF', 'Nominal TO',
                  'Total_Mutasi', 'Selisih_Final', 'Jumlah_Titik_Mutasi']
kolom_numerik = [c for c in kolom_numerik if c in audit_df.columns]
audit_df[kolom_numerik] = audit_df[kolom_numerik].apply(pd.to_numeric, errors='coerce').fillna(0)

# Hapus baris yang benar-benar duplikat penuh
jumlah_sebelum = len(audit_df)
audit_df = audit_df.drop_duplicates().reset_index(drop=True)
print(f"\nBaris duplikat yang dihapus: {jumlah_sebelum - len(audit_df)}")

print("\nJumlah missing value per kolom SETELAH penanganan:")
print(audit_df.isna().sum())

### 5.1.2 Feature Engineering dari Kolom Tanggal

In [ ]:
# FEATURE ENGINEERING: EKSTRAKSI KOMPONEN TANGGAL
audit_df['Tanggal'] = pd.to_datetime(audit_df['Tanggal'], errors='coerce')
audit_df['Hari'] = audit_df['Tanggal'].dt.day
audit_df['Hari_dalam_Minggu'] = audit_df['Tanggal'].dt.dayofweek  # 0=Senin ... 6=Minggu
audit_df['Akhir_Pekan'] = audit_df['Hari_dalam_Minggu'].isin([5, 6]).astype(int)

audit_df[['Tanggal', 'Hari', 'Hari_dalam_Minggu', 'Akhir_Pekan']].head()

### 5.1.3 Deteksi Outlier pada Nominal Transaksi (Metode IQR)

In [ ]:
# DETEKSI OUTLIER DENGAN METODE IQR
Q1 = audit_df['Total_Mutasi'].quantile(0.25)
Q3 = audit_df['Total_Mutasi'].quantile(0.75)
IQR = Q3 - Q1
batas_bawah = Q1 - 1.5 * IQR
batas_atas = Q3 + 1.5 * IQR

audit_df['Is_Outlier_Nominal'] = (~audit_df['Total_Mutasi'].between(batas_bawah, batas_atas)).astype(int)

print(f"Batas bawah wajar : Rp {batas_bawah:,.0f}")
print(f"Batas atas wajar  : Rp {batas_atas:,.0f}")
print(f"Jumlah transaksi terindikasi outlier: {audit_df['Is_Outlier_Nominal'].sum()} dari {len(audit_df)} baris")

# Catatan: outlier TIDAK dihapus dari dataset. Nominal transaksi yang jauh
# dari kebiasaan justru merupakan sinyal penting untuk deteksi anomali/fraud,
# sehingga cukup ditandai sebagai fitur baru (Is_Outlier_Nominal).

### 5.1.4 Encoding Data Kategorikal

In [ ]:
# ENCODING FITUR KATEGORIKAL
from sklearn.preprocessing import LabelEncoder

le_jenis_bayar = LabelEncoder()
audit_df['Jenis_Bayar_Encoded'] = le_jenis_bayar.fit_transform(audit_df['Jenis Bayar'])
print("Mapping Jenis Bayar:",
      dict(zip(le_jenis_bayar.classes_, le_jenis_bayar.transform(le_jenis_bayar.classes_))))

if 'Akun Closing' in audit_df.columns:
    le_akun_closing = LabelEncoder()
    audit_df['Akun_Closing_Encoded'] = le_akun_closing.fit_transform(audit_df['Akun Closing'])
    print("\nMapping Akun Closing:",
          dict(zip(le_akun_closing.classes_, le_akun_closing.transform(le_akun_closing.classes_))))

# Target_ML sudah dalam bentuk numerik hasil pd.factorize() pada tahap sebelumnya,
# sehingga tidak perlu di-encode ulang. Simpan pemetaan labelnya untuk interpretasi:
label_mapping = {i: label for i, label in enumerate(unik_labels)}
print("\nMapping Target_ML -> Label_Kategori:")
for k, v in label_mapping.items():
    print(f"  {k}: {v}")

### 5.1.5 Feature Scaling (Standarisasi Nominal)

In [ ]:
# FEATURE SCALING DENGAN StandardScaler
from sklearn.preprocessing import StandardScaler

fitur_numerik_scale = ['Nominal CL', 'Nominal AK', 'Nominal TF', 'Nominal TO',
                        'Total_Mutasi', 'Selisih_Final']
fitur_numerik_scale = [c for c in fitur_numerik_scale if c in audit_df.columns]

scaler = StandardScaler()
fitur_scaled = pd.DataFrame(
    scaler.fit_transform(audit_df[fitur_numerik_scale]),
    columns=[f"{c}_scaled" for c in fitur_numerik_scale],
    index=audit_df.index
)

audit_df_final = pd.concat([audit_df, fitur_scaled], axis=1)
audit_df_final.head()

### 5.1.6 Train-Test Split

In [ ]:
# TRAIN-TEST SPLIT
from sklearn.model_selection import train_test_split

fitur_model = (
    [f"{c}_scaled" for c in fitur_numerik_scale]
    + ['Jumlah_Titik_Mutasi', 'Hari', 'Hari_dalam_Minggu', 'Akhir_Pekan',
       'Is_Outlier_Nominal', 'Jenis_Bayar_Encoded']
)
if 'Akun_Closing_Encoded' in audit_df_final.columns:
    fitur_model.append('Akun_Closing_Encoded')

X = audit_df_final[fitur_model]
y = audit_df_final['Target_ML']

# Beberapa kategori label kemungkinan hanya punya sedikit anggota (sangat imbalance),
# sehingga stratifikasi hanya digunakan bila setiap kelas punya >= 2 anggota.
kelas_cukup_untuk_stratify = y.value_counts().min() >= 2

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y if kelas_cukup_untuk_stratify else None
)

print(f"Ukuran data latih (X_train): {X_train.shape}")
print(f"Ukuran data uji   (X_test) : {X_test.shape}")
print("\nDistribusi label pada data latih:")
print(y_train.value_counts())

### 5.1.7 Simpan Dataset Hasil Preprocessing & Artefak (Scaler/Encoder)

In [ ]:
# SIMPAN DATASET SIAP MODELING + ARTEFAK PREPROCESSING
import joblib
import json as _json
import os

output_dir = '/content/preprocessing_output'
os.makedirs(output_dir, exist_ok=True)

X_train.to_csv(f'{output_dir}/X_train.csv', index=False)
X_test.to_csv(f'{output_dir}/X_test.csv', index=False)
y_train.to_csv(f'{output_dir}/y_train.csv', index=False)
y_test.to_csv(f'{output_dir}/y_test.csv', index=False)
audit_df_final.to_csv(f'{output_dir}/audit_df_preprocessed.csv', index=False)

joblib.dump(scaler, f'{output_dir}/scaler.joblib')
joblib.dump(le_jenis_bayar, f'{output_dir}/label_encoder_jenis_bayar.joblib')
if 'le_akun_closing' in dir():
    joblib.dump(le_akun_closing, f'{output_dir}/label_encoder_akun_closing.joblib')

with open(f'{output_dir}/label_mapping.json', 'w') as f:
    _json.dump(label_mapping, f, indent=2, ensure_ascii=False)

print("Seluruh data hasil preprocessing & artefak (scaler, encoder, mapping label) tersimpan di:")
print(output_dir)
print("\nIsi folder:")
for fname in sorted(os.listdir(output_dir)):
    print(" -", fname)